---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oadp-vm-file-restore-controller-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oadp.openshift.io
  resources:
  - virtualmachinebackupsdiscoveries
  - virtualmachinefilerestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oadp.openshift.io
  resources:
  - virtualmachinebackupsdiscoveries/finalizers
  - virtualmachinefilerestores/finalizers
  verbs:
  - update
- apiGroups:
  - oadp.openshift.io
  resources:
  - virtualmachinebackupsdiscoveries/status
  - virtualmachinefilerestores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - velero.io
  resources:
  - backups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - velero.io
  resources:
  - datadownloads
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - velero.io
  resources:
  - downloadrequests
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - velero.io
  resources:
  - restores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
