#!/bin/bash
# Analyze test failures with Claude via Vertex AI after Ginkgo suite completes
# Only runs if tests failed and Claude analysis is not skipped

set +e  # Don't exit on Claude failure

ARTIFACT_DIR=${ARTIFACT_DIR:-/tmp}
SKIP_CLAUDE=${SKIP_CLAUDE_ANALYSIS:-false}
EXIT_CODE=$1

# Redact sensitive information from logs and output
# Redacts: API keys, tokens, passwords, service account keys, AWS credentials
redact_secrets() {
    sed -E \
        -e 's/AKIA[0-9A-Z]{16}/[REDACTED-AWS-ACCESS-KEY]/g' \
        -e 's/(aws_secret_access_key[" :=]+)[A-Za-z0-9/+=]{40}/\1[REDACTED-AWS-SECRET]/g' \
        -e 's/"private_key": ?"-----BEGIN[^"]*END[^"]*"/"private_key": "[REDACTED-GCP-PRIVATE-KEY]"/g' \
        -e 's/Bearer +[A-Za-z0-9._~+-]+=*/Bearer [REDACTED-TOKEN]/g' \
        -e 's/(password[" :=]+)[^ "'\'']+/\1[REDACTED-PASSWORD]/gi' \
        -e 's/(passwd[" :=]+)[^ "'\'']+/\1[REDACTED-PASSWORD]/gi' \
        -e 's/(api[_-]?key[" :=]+)[^ "'\'']+/\1[REDACTED-APIKEY]/gi' \
        -e 's/(token[" :=]+)[A-Za-z0-9._~+-]+=*/\1[REDACTED-TOKEN]/gi' \
        -e 's/(secret[" :=]+)[^ "'\'']{16,}/\1[REDACTED-SECRET]/gi' \
        -e 's/eyJ[A-Za-z0-9_-]*\.eyJ[A-Za-z0-9_-]*\.[A-Za-z0-9_-]*/[REDACTED-JWT-TOKEN]/g' \
        -e 's/-----BEGIN (RSA |EC )?PRIVATE KEY-----[^-]*-----END (RSA |EC )?PRIVATE KEY-----/[REDACTED-PRIVATE-KEY]/g' \
        -e 's/(client[_-]?secret[" :=]+)[^ "'\'']+/\1[REDACTED-CLIENT-SECRET]/gi' \
        -e 's/(authorization[" :]+)[^ "'\'']+/\1[REDACTED-AUTH]/gi'
}

# Verify Vertex AI configuration
if [ -z "$GOOGLE_APPLICATION_CREDENTIALS" ] || [ -z "$ANTHROPIC_VERTEX_PROJECT_ID" ]; then
    echo "⚠ Vertex AI not configured (missing GOOGLE_APPLICATION_CREDENTIALS or ANTHROPIC_VERTEX_PROJECT_ID)"
    echo "Skipping Claude analysis"
    exit $EXIT_CODE
fi

if [ "$SKIP_CLAUDE" = "true" ]; then
    echo "Claude analysis skipped (SKIP_CLAUDE_ANALYSIS=true)"
    exit $EXIT_CODE
fi

if [ $EXIT_CODE -ne 0 ]; then
    echo "=== Test failures detected, invoking Claude analysis via Vertex AI ==="
    echo "GCP Project: $ANTHROPIC_VERTEX_PROJECT_ID"
    echo "Vertex AI Region: ${CLOUD_ML_REGION:-global}"
    echo "ARTIFACT_DIR: $ARTIFACT_DIR"

    # Find build-log.txt (typically in parent directory of ARTIFACT_DIR)
    BUILD_LOG="${ARTIFACT_DIR}/../build-log.txt"
    if [ ! -f "$BUILD_LOG" ]; then
        BUILD_LOG="/logs/build-log.txt"
    fi

    if [ ! -f "$BUILD_LOG" ]; then
        echo "Warning: build-log.txt not found at expected locations"
        BUILD_LOG="<not available>"
    fi

    # Create analysis prompt
    cat > "${ARTIFACT_DIR}/claude-prompt.txt" << 'PROMPT_EOF'
# OADP E2E Test Failure Analysis Request

You are analyzing a failed OADP (OpenShift API for Data Protection) E2E test run from Prow CI.

## Available Artifacts

1. **build-log.txt**: Complete Ginkgo test output (stdout/stderr) - contains all test execution logs
2. **must-gather/**: OADP diagnostics collection with structure:
   - `clusters/<cluster-id>/oadp-must-gather-summary.md` - High-level summary
   - `clusters/<cluster-id>/namespaces/openshift-adp/` - OADP namespace resources (pod logs, DPA, BSL, VSL, backups, restores)
   - `clusters/<cluster-id>/cluster-scoped-resources/` - Cluster-wide resources (CSI drivers, storage classes)
3. **junit_report.xml**: Structured test results with pass/fail status
4. **<TestName>/**: Per-test directories containing:
   - `openshift-adp/<pod-name>/*.log` - Velero, node-agent, plugin logs
   - `<app-namespace>/<pod-name>/*.log` - Application pod logs

## Known Flake Patterns (see tests/e2e/lib/flakes.go)

Check for these known flakes before diagnosing as real failures:
- "Failed to check and update snapshot content" - CSI VolumeSnapshotBeingCreated race condition (issue #876)
- "Error copying image: writing blob" - Transient S3 bucket errors (issue #5856)
- AWS rate limiting errors
- DNS resolution timeouts
- Image pull backoff errors

## Analysis Tasks

1. Parse junit_report.xml to identify all failed tests
2. For each failed test:
   a. Extract relevant log snippets from build-log.txt (search by test name)
   b. Review must-gather diagnostics for OADP component status
   c. Check per-test pod logs for error messages
   d. Identify root cause (real bug vs known flake vs environmental issue)
   e. Provide evidence-based diagnosis with line numbers/log snippets
3. Summarize overall cluster health from must-gather
4. Provide actionable recommendations prioritized by severity

## Output Format

Generate a markdown document with this exact structure:

```markdown
# OADP E2E Test Failure Analysis
*Generated by Claude via Vertex AI on <timestamp>*

## Executive Summary
- **Total Tests**: X
- **Failed Tests**: Y
- **Known Flakes**: Z
- **Critical Issues**: N (real bugs requiring immediate attention)
- **Environmental Issues**: M (transient cloud/cluster issues)

## Failed Tests Analysis

### 1. <TestName> [CRITICAL|WARNING|FLAKE|ENVIRONMENTAL]

**Root Cause**: <One-sentence summary>

**Evidence**:
```
build-log.txt:LINE: "<relevant log excerpt>"
must-gather: <specific resource status or log finding>
Pod logs (<namespace>/<pod>/<container>): "<error message>"
```

**Diagnosis**: <Detailed analysis of what went wrong and why>

**Likely Cause**: <Environmental/bug/config/flake with reasoning>

**Recommended Actions**:
1. <Specific action with details>
2. <Specific action with details>

**Related Issues**: <GitHub issue links if pattern matches known issues>

---

### 2. <Next Failed Test> [...]

[Repeat for each failed test]

## Known Flakes Detected

- ✓ VolumeSnapshotBeingCreated race condition (matched pattern in build-log.txt:LINES)
- ✗ AWS rate limiting (not detected)

## Cluster Health Summary

From must-gather analysis:

**OADP Components**:
- Velero deployment: <status, restart count, resource usage>
- Node Agent daemonset: <X/Y running, any issues>
- Backup Storage Location: <Available/Unavailable, last sync time>
- Volume Snapshot Location: <Available/Unavailable, provider status>

**Cluster Resources**:
- CSI drivers: <driver names and status>
- Storage classes: <available SCs>
- Resource pressure: <CPU/memory/storage issues if any>

**Recent Events**:
<Significant namespace events from must-gather>

## Recommendations (Prioritized)

### Immediate Actions (Critical)
1. <Action for critical bug>
2. <Action for critical bug>

### Investigation Needed
1. <Item requiring further investigation>
2. <Item requiring further investigation>

### Flake Handling
1. <Suggestion for known flakes>

### Configuration Review
1. <Config changes that might help>

## Analysis Confidence

- **High Confidence**: <List tests where root cause is clear>
- **Medium Confidence**: <List tests needing more data>
- **Low Confidence**: <List tests with ambiguous failures>

## Suggested Next Steps for Developer

1. Review critical issues first (prioritized above)
2. Check if failures match existing GitHub issues
3. Re-run flakes to confirm transient nature
4. Investigate environmental issues in cluster/cloud provider
```

## Important Guidelines

- Be specific: Always cite line numbers from build-log.txt, not "somewhere in the log"
- Be evidence-based: Don't speculate without supporting log evidence
- Distinguish failure types: Real bugs vs flakes vs environmental vs configuration
- Be actionable: Recommendations should be concrete and implementable
- Be concise: Developers need quick insights, not verbose analysis
- Cross-reference: Link similar failures across multiple tests
- Prioritize: Put critical issues before warnings before flakes
PROMPT_EOF

    # Count failed tests from JUnit
    FAILED_COUNT=0
    if [ -f "${ARTIFACT_DIR}/junit_report.xml" ]; then
        FAILED_COUNT=$(grep -c 'failures="[1-9]' "${ARTIFACT_DIR}/junit_report.xml" 2>/dev/null || echo "0")
    fi

    echo "Found $FAILED_COUNT test suites with failures"
    echo "Invoking Claude for analysis..."

    # Invoke Claude via Vertex AI with secret redaction
    # Claude Code CLI uses Vertex AI when CLAUDE_CODE_USE_VERTEX=1 and credentials are set
    # Output is redacted to prevent credential leakage
    # Using --print flag for headless/non-interactive mode suitable for CI automation
    timeout 600 claude --print "You are analyzing OADP E2E test failures from Prow CI.

Read the analysis instructions in: ${ARTIFACT_DIR}/claude-prompt.txt

Analyze these artifacts:
1. Build log: ${BUILD_LOG}
2. Must-gather: ${ARTIFACT_DIR}/must-gather/
3. JUnit report: ${ARTIFACT_DIR}/junit_report.xml
4. Test failure directories: ${ARTIFACT_DIR}/*/

Generate comprehensive failure analysis following the output format specified in the prompt.
Focus on actionable insights and clear root cause identification.

IMPORTANT SECURITY NOTE:
Do NOT include any API keys, tokens, passwords, or service account keys in your analysis.
If you encounter credentials in logs, reference them generically (e.g., \"AWS credentials found in log\")." 2>&1 | redact_secrets > "${ARTIFACT_DIR}/claude-failure-analysis.md"

    CLAUDE_EXIT=$?

    if [ $CLAUDE_EXIT -eq 0 ]; then
        echo "✓ Claude analysis completed successfully (with secret redaction)"
        echo "✓ Analysis saved to: ${ARTIFACT_DIR}/claude-failure-analysis.md"

        # Show summary (first 80 lines) - also redacted
        echo ""
        echo "=== Claude Analysis Preview ==="
        head -80 "${ARTIFACT_DIR}/claude-failure-analysis.md" | redact_secrets
        echo "=== (Full analysis available in Prow artifacts) ==="
    elif [ $CLAUDE_EXIT -eq 124 ]; then
        echo "✗ Claude analysis timed out after 10 minutes"
        echo "Large build-log.txt may have exceeded token limits"
        echo "Partial analysis may be in ${ARTIFACT_DIR}/claude-failure-analysis.md"
    else
        echo "✗ Claude analysis failed (exit code: $CLAUDE_EXIT)"
        echo "Check ${ARTIFACT_DIR}/claude-failure-analysis.md for error details"
    fi

    # Cleanup prompt (keep in artifacts for debugging)
    # rm -f "${ARTIFACT_DIR}/claude-prompt.txt"
else
    echo "Tests passed, skipping Claude analysis"
fi

exit $EXIT_CODE
