apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: oadp-operator
spec:
  groups:
  - name: oadp-operator.rules
    rules:
    - expr: max without(instance) (velero_restore_total)
      record: cluster:velero_restore_total:max
    - expr: max without(instance) (velero_backup_total)
      record: cluster:velero_backup_total:max