apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: openshift-adp-cli-server
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: oadp-cli
  type: ClusterIP
status:
  loadBalancer: {}
