apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oadp-vm-file-restore
  name: virtualmachinebackupsdiscovery-viewer-role
rules:
- apiGroups:
  - oadp.openshift.io
  resources:
  - virtualmachinebackupsdiscoveries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oadp.openshift.io
  resources:
  - virtualmachinebackupsdiscoveries/status
  verbs:
  - get
