#!/bin/bash

skip_tls="${1:-false}"

for pod in $(oc get pods --insecure-skip-tls-verify=${skip_tls} -n openshift-adp -o jsonpath='{.items[?(.status.containerStatuses[0].lastState.terminated.reason=="Error")].metadata.name}'); do
    echo "***"
    echo "* Last logs from failed pod openshift-adp/${pod}:"
    oc logs -n openshift-adp --insecure-skip-tls-verify=${skip_tls} $pod --tail=10
    echo -e "\n\n\n"
done
