apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: project-template
  annotations:
    description: "Create the project and namespace"
parameters:
  - name: BASENAME
    description: The name of the project
    value: foo
  - name: USER
    description: user with rights to launch pipelines
  - name: PROJECT
    description: The project where users have view access
objects:
  - kind: User
    apiVersion: user.openshift.io/v1
    metadata:
      name: '${USER}'
    identities:
      - '${BASENAME}:${USER}'
  - kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: view
      namespace: ${PROJECT}
    subjects:
      - kind: User
        apiGroup: rbac.authorization.k8s.io
        name: ${USER}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: view
    name: view


