# permissions for end users to view dataprotectiontests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: oadp-operator
    app.kubernetes.io/managed-by: kustomize
  name: dataprotectiontest-viewer-role
rules:
- apiGroups:
  - oadp.openshift.io
  resources:
  - dataprotectiontests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oadp.openshift.io
  resources:
  - dataprotectiontests/status
  verbs:
  - get
