name: Bug Report
description: File a bug report
title: "Bug: "
labels: ["kind/bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe bug
      description: and also tell us how to reproduce!
      placeholder: A bug happened when I ate cereal!
      value: "A bug happened when I ate cereal!"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: A bug happened!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: oadp-version
    attributes:
      label: OADP Version
      description: What version of our software are you running?
      options:
        - 0.3.x (Beta)
        - 0.2.x (Alpha)
    validations:
      required: true
  - type: dropdown
    id: ocp-version
    attributes:
      label: OpenShift Version
      description: What version of OpenShift are you running?
      options:
        - 4.9
        - 4.8
        - 4.7
        - 4.6
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        To get logs run the following
        `$ oc logs <pod_name> -n openshift-adp`
        Pod names can be found by
        `$ oc get pods -n openshift-adp`
  - type: textarea
    id: velero-logs
    attributes:
      label: Velero pod logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: restic-logs
    attributes:
      label: Restic pod logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: operator-logs
    attributes:
      label: Operator pod logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: new-issue
    attributes:
      label: New issue
      description: By submitting this issue, you assert that this issue is new and [have not already been filed.](https://github.com/openshift/oadp-operator/issues)
      options:
        - label: This issue is new
          required: true
