#
# This Template provides fill access to all velero.io resources.
# It is NOT recommended to give restore access rights to non-admin users.
# For security purposes the default template will ONLY provide backup rights.
#
#
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: project-template
  annotations:
    description: "Create the project and namespace"
parameters:
  - name: PROJECT
    description: The name of the project
  - name: USER
    description: user with rights to launch b/r pipelines
objects:
  # This manifest gives tekton the permission to execute velero backups and restore 
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: oadp-nonadmin-role
  rules:
  - apiGroups:
    # By default restore resources will NOT be provided by this template.
    # It is recommended that restores are executed by OpenShift Admin's in production environments.
    # For demonstration purposes only you may uncomment the restore resources.
    - velero.io
    resources:
    - 'backuprepositories'
    - 'backups'
    # - 'deletebackuprequests'
    # - 'downloadrequests'
    - 'podvolumebackups'
    # - 'podvolumerestores'
    # - 'restores'
    # - 'schedules'
    - 'serverstatusrequests'
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
    # Non-Admin users should NOT be able to create a backupstoragelocation (BSL) or volumesnapshotlocation (VSL).
    # Only OpenShift Administrators should create a BSL or VSL.
  - apiGroups:
    - velero.io
    resources:
    - 'backupstoragelocations'
    - 'volumesnapshotlocations'
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - image.openshift.io
    resources:
    - "images"
    verbs:
    - "get"
    - "patch"
  - apiGroups:
    - image.openshift.io
    resources:
    - "imagesteams"
    verbs:
    - "get"
    - "patch"
  
    # This role gives a non-admin user permission to execute tekton pipelines, but
    # not to edit the pipeline.
- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: oadp-pipeline-runner
    namespace: ${PROJECT}
  rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns"]
    verbs: ["*"]
