apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: project-template
  annotations:
    description: "Create the project and namespace"
parameters:
  - name: PROJECT
    description: The name of the project
  - name: USER
    description: user with rights to launch b/r pipelines
objects:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: pipeline-${PROJECT}-role-binding-oadp-non-admin
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: oadp-nonadmin-role
  subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: ${PROJECT}

- kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: ${PROJECT}-pipeline-runner-binding
    namespace: ${PROJECT}
  subjects:
    - kind: User
      apiGroup: rbac.authorization.k8s.io
      name: ${USER}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: oadp-pipeline-runner

