#!/bin/bash
echo "This script is deprecated, use /usr/bin/gather instead"
logs_since="${logs_since}"
skip_tls="${skip_tls}"
request_timeout="${request_timeout}"
if [ ! -z "${logs_since}" ]; then
    echo "logs_since variable is not supported anymore"
    exit 1
fi
if [ ! -z "${skip_tls}" ] && [ ! -z "${request_timeout}" ]; then
    echo "insecure-skip-tls-verify: ${skip_tls}"
    echo "timeout: ${request_timeout}"
    /usr/bin/gather --skip-tls=${skip_tls} --request-timeout=${request_timeout}
    exit
fi
if [ ! -z "${skip_tls}" ]; then
    echo "insecure-skip-tls-verify: ${skip_tls}"
    /usr/bin/gather --skip-tls=${skip_tls}
    exit
fi
if [ ! -z "${request_timeout}" ]; then
    echo "timeout: ${request_timeout}"
    /usr/bin/gather --request-timeout=${request_timeout}
    exit
fi
/usr/bin/gather
