apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: velero-sample
spec:
  enableDataMover: true
  configuration:
    velero:
      defaultPlugins:
      - openshift
      - aws
      - csi
    restic:
      enable: true
  backupLocations:
    - velero:
        provider: aws
        default: true
        objectStorage:
          bucket: shubbam-6109f5e9711c8c58131acdd2f490f451
          prefix: velero
        config:
          region: us-east-1
          profile: "default"
        credential:
          name: cloud-credentials
          key: cloud
  snapshotLocations:
    - velero:  
        provider: aws
        config:
          region: us-west-2
          profile: "default"
