//go:build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/openshift/oadp-operator/pkg/velero/server"
	"github.com/vmware-tanzu/velero/pkg/apis/velero/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationConfig) DeepCopyInto(out *ApplicationConfig) {
	*out = *in
	if in.Velero != nil {
		in, out := &in.Velero, &out.Velero
		*out = new(VeleroConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Restic != nil {
		in, out := &in.Restic, &out.Restic
		*out = new(ResticConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeAgent != nil {
		in, out := &in.NodeAgent, &out.NodeAgent
		*out = new(NodeAgentConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationConfig.
func (in *ApplicationConfig) DeepCopy() *ApplicationConfig {
	if in == nil {
		return nil
	}
	out := new(ApplicationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupLocation) DeepCopyInto(out *BackupLocation) {
	*out = *in
	if in.Velero != nil {
		in, out := &in.Velero, &out.Velero
		*out = new(v1.BackupStorageLocationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CloudStorage != nil {
		in, out := &in.CloudStorage, &out.CloudStorage
		*out = new(CloudStorageLocation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupLocation.
func (in *BackupLocation) DeepCopy() *BackupLocation {
	if in == nil {
		return nil
	}
	out := new(BackupLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudStorage) DeepCopyInto(out *CloudStorage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudStorage.
func (in *CloudStorage) DeepCopy() *CloudStorage {
	if in == nil {
		return nil
	}
	out := new(CloudStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudStorage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudStorageList) DeepCopyInto(out *CloudStorageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudStorage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudStorageList.
func (in *CloudStorageList) DeepCopy() *CloudStorageList {
	if in == nil {
		return nil
	}
	out := new(CloudStorageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudStorageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudStorageLocation) DeepCopyInto(out *CloudStorageLocation) {
	*out = *in
	out.CloudStorageRef = in.CloudStorageRef
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Credential != nil {
		in, out := &in.Credential, &out.Credential
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.BackupSyncPeriod != nil {
		in, out := &in.BackupSyncPeriod, &out.BackupSyncPeriod
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.CACert != nil {
		in, out := &in.CACert, &out.CACert
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudStorageLocation.
func (in *CloudStorageLocation) DeepCopy() *CloudStorageLocation {
	if in == nil {
		return nil
	}
	out := new(CloudStorageLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudStorageSpec) DeepCopyInto(out *CloudStorageSpec) {
	*out = *in
	in.CreationSecret.DeepCopyInto(&out.CreationSecret)
	if in.EnableSharedConfig != nil {
		in, out := &in.EnableSharedConfig, &out.EnableSharedConfig
		*out = new(bool)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudStorageSpec.
func (in *CloudStorageSpec) DeepCopy() *CloudStorageSpec {
	if in == nil {
		return nil
	}
	out := new(CloudStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudStorageStatus) DeepCopyInto(out *CloudStorageStatus) {
	*out = *in
	if in.LastSynced != nil {
		in, out := &in.LastSynced, &out.LastSynced
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudStorageStatus.
func (in *CloudStorageStatus) DeepCopy() *CloudStorageStatus {
	if in == nil {
		return nil
	}
	out := new(CloudStorageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomPlugin) DeepCopyInto(out *CustomPlugin) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomPlugin.
func (in *CustomPlugin) DeepCopy() *CustomPlugin {
	if in == nil {
		return nil
	}
	out := new(CustomPlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataMover) DeepCopyInto(out *DataMover) {
	*out = *in
	if in.VolumeOptionsForStorageClasses != nil {
		in, out := &in.VolumeOptionsForStorageClasses, &out.VolumeOptionsForStorageClasses
		*out = make(map[string]DataMoverVolumeOptions, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.SnapshotRetainPolicy != nil {
		in, out := &in.SnapshotRetainPolicy, &out.SnapshotRetainPolicy
		*out = new(RetainPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataMover.
func (in *DataMover) DeepCopy() *DataMover {
	if in == nil {
		return nil
	}
	out := new(DataMover)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataMoverDataDownloads) DeepCopyInto(out *DataMoverDataDownloads) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataMoverDataDownloads.
func (in *DataMoverDataDownloads) DeepCopy() *DataMoverDataDownloads {
	if in == nil {
		return nil
	}
	out := new(DataMoverDataDownloads)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataMoverDataUploads) DeepCopyInto(out *DataMoverDataUploads) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataMoverDataUploads.
func (in *DataMoverDataUploads) DeepCopy() *DataMoverDataUploads {
	if in == nil {
		return nil
	}
	out := new(DataMoverDataUploads)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataMoverVolumeOptions) DeepCopyInto(out *DataMoverVolumeOptions) {
	*out = *in
	if in.SourceVolumeOptions != nil {
		in, out := &in.SourceVolumeOptions, &out.SourceVolumeOptions
		*out = new(VolumeOptions)
		**out = **in
	}
	if in.DestinationVolumeOptions != nil {
		in, out := &in.DestinationVolumeOptions, &out.DestinationVolumeOptions
		*out = new(VolumeOptions)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataMoverVolumeOptions.
func (in *DataMoverVolumeOptions) DeepCopy() *DataMoverVolumeOptions {
	if in == nil {
		return nil
	}
	out := new(DataMoverVolumeOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataProtectionApplication) DeepCopyInto(out *DataProtectionApplication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataProtectionApplication.
func (in *DataProtectionApplication) DeepCopy() *DataProtectionApplication {
	if in == nil {
		return nil
	}
	out := new(DataProtectionApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataProtectionApplication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataProtectionApplicationList) DeepCopyInto(out *DataProtectionApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataProtectionApplication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataProtectionApplicationList.
func (in *DataProtectionApplicationList) DeepCopy() *DataProtectionApplicationList {
	if in == nil {
		return nil
	}
	out := new(DataProtectionApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataProtectionApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataProtectionApplicationSpec) DeepCopyInto(out *DataProtectionApplicationSpec) {
	*out = *in
	if in.BackupLocations != nil {
		in, out := &in.BackupLocations, &out.BackupLocations
		*out = make([]BackupLocation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SnapshotLocations != nil {
		in, out := &in.SnapshotLocations, &out.SnapshotLocations
		*out = make([]SnapshotLocation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UnsupportedOverrides != nil {
		in, out := &in.UnsupportedOverrides, &out.UnsupportedOverrides
		*out = make(map[UnsupportedImageKey]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.PodDnsConfig.DeepCopyInto(&out.PodDnsConfig)
	if in.BackupImages != nil {
		in, out := &in.BackupImages, &out.BackupImages
		*out = new(bool)
		**out = **in
	}
	if in.Configuration != nil {
		in, out := &in.Configuration, &out.Configuration
		*out = new(ApplicationConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = new(Features)
		(*in).DeepCopyInto(*out)
	}
	if in.ImagePullPolicy != nil {
		in, out := &in.ImagePullPolicy, &out.ImagePullPolicy
		*out = new(corev1.PullPolicy)
		**out = **in
	}
	if in.NonAdmin != nil {
		in, out := &in.NonAdmin, &out.NonAdmin
		*out = new(NonAdmin)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataProtectionApplicationSpec.
func (in *DataProtectionApplicationSpec) DeepCopy() *DataProtectionApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(DataProtectionApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataProtectionApplicationStatus) DeepCopyInto(out *DataProtectionApplicationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataProtectionApplicationStatus.
func (in *DataProtectionApplicationStatus) DeepCopy() *DataProtectionApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(DataProtectionApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnforceBackupStorageLocationSpec) DeepCopyInto(out *EnforceBackupStorageLocationSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Credential != nil {
		in, out := &in.Credential, &out.Credential
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	in.StorageType.DeepCopyInto(&out.StorageType)
	if in.BackupSyncPeriod != nil {
		in, out := &in.BackupSyncPeriod, &out.BackupSyncPeriod
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.ValidationFrequency != nil {
		in, out := &in.ValidationFrequency, &out.ValidationFrequency
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnforceBackupStorageLocationSpec.
func (in *EnforceBackupStorageLocationSpec) DeepCopy() *EnforceBackupStorageLocationSpec {
	if in == nil {
		return nil
	}
	out := new(EnforceBackupStorageLocationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Features) DeepCopyInto(out *Features) {
	*out = *in
	if in.DataMover != nil {
		in, out := &in.DataMover, &out.DataMover
		*out = new(DataMover)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Features.
func (in *Features) DeepCopy() *Features {
	if in == nil {
		return nil
	}
	out := new(Features)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileSystemPodVolumeBackups) DeepCopyInto(out *FileSystemPodVolumeBackups) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileSystemPodVolumeBackups.
func (in *FileSystemPodVolumeBackups) DeepCopy() *FileSystemPodVolumeBackups {
	if in == nil {
		return nil
	}
	out := new(FileSystemPodVolumeBackups)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileSystemPodVolumeRestores) DeepCopyInto(out *FileSystemPodVolumeRestores) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileSystemPodVolumeRestores.
func (in *FileSystemPodVolumeRestores) DeepCopy() *FileSystemPodVolumeRestores {
	if in == nil {
		return nil
	}
	out := new(FileSystemPodVolumeRestores)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAgentCommonFields) DeepCopyInto(out *NodeAgentCommonFields) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.SupplementalGroups != nil {
		in, out := &in.SupplementalGroups, &out.SupplementalGroups
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.PodConfig != nil {
		in, out := &in.PodConfig, &out.PodConfig
		*out = new(PodConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAgentCommonFields.
func (in *NodeAgentCommonFields) DeepCopy() *NodeAgentCommonFields {
	if in == nil {
		return nil
	}
	out := new(NodeAgentCommonFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAgentConfig) DeepCopyInto(out *NodeAgentConfig) {
	*out = *in
	in.NodeAgentCommonFields.DeepCopyInto(&out.NodeAgentCommonFields)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAgentConfig.
func (in *NodeAgentConfig) DeepCopy() *NodeAgentConfig {
	if in == nil {
		return nil
	}
	out := new(NodeAgentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdmin) DeepCopyInto(out *NonAdmin) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.EnforceBackupSpec != nil {
		in, out := &in.EnforceBackupSpec, &out.EnforceBackupSpec
		*out = new(v1.BackupSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.EnforceRestoreSpec != nil {
		in, out := &in.EnforceRestoreSpec, &out.EnforceRestoreSpec
		*out = new(v1.RestoreSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.EnforceBSLSpec != nil {
		in, out := &in.EnforceBSLSpec, &out.EnforceBSLSpec
		*out = new(EnforceBackupStorageLocationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RequireApprovalForBSL != nil {
		in, out := &in.RequireApprovalForBSL, &out.RequireApprovalForBSL
		*out = new(bool)
		**out = **in
	}
	if in.GarbageCollectionPeriod != nil {
		in, out := &in.GarbageCollectionPeriod, &out.GarbageCollectionPeriod
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.BackupSyncPeriod != nil {
		in, out := &in.BackupSyncPeriod, &out.BackupSyncPeriod
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdmin.
func (in *NonAdmin) DeepCopy() *NonAdmin {
	if in == nil {
		return nil
	}
	out := new(NonAdmin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminBackup) DeepCopyInto(out *NonAdminBackup) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminBackup.
func (in *NonAdminBackup) DeepCopy() *NonAdminBackup {
	if in == nil {
		return nil
	}
	out := new(NonAdminBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NonAdminBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminBackupList) DeepCopyInto(out *NonAdminBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NonAdminBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminBackupList.
func (in *NonAdminBackupList) DeepCopy() *NonAdminBackupList {
	if in == nil {
		return nil
	}
	out := new(NonAdminBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NonAdminBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminBackupSpec) DeepCopyInto(out *NonAdminBackupSpec) {
	*out = *in
	if in.BackupSpec != nil {
		in, out := &in.BackupSpec, &out.BackupSpec
		*out = new(v1.BackupSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminBackupSpec.
func (in *NonAdminBackupSpec) DeepCopy() *NonAdminBackupSpec {
	if in == nil {
		return nil
	}
	out := new(NonAdminBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminBackupStatus) DeepCopyInto(out *NonAdminBackupStatus) {
	*out = *in
	if in.VeleroBackup != nil {
		in, out := &in.VeleroBackup, &out.VeleroBackup
		*out = new(VeleroBackup)
		(*in).DeepCopyInto(*out)
	}
	if in.VeleroDeleteBackupRequest != nil {
		in, out := &in.VeleroDeleteBackupRequest, &out.VeleroDeleteBackupRequest
		*out = new(VeleroDeleteBackupRequest)
		(*in).DeepCopyInto(*out)
	}
	if in.DataMoverDataUploads != nil {
		in, out := &in.DataMoverDataUploads, &out.DataMoverDataUploads
		*out = new(DataMoverDataUploads)
		**out = **in
	}
	if in.FileSystemPodVolumeBackups != nil {
		in, out := &in.FileSystemPodVolumeBackups, &out.FileSystemPodVolumeBackups
		*out = new(FileSystemPodVolumeBackups)
		**out = **in
	}
	if in.QueueInfo != nil {
		in, out := &in.QueueInfo, &out.QueueInfo
		*out = new(QueueInfo)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminBackupStatus.
func (in *NonAdminBackupStatus) DeepCopy() *NonAdminBackupStatus {
	if in == nil {
		return nil
	}
	out := new(NonAdminBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminBackupStorageLocation) DeepCopyInto(out *NonAdminBackupStorageLocation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminBackupStorageLocation.
func (in *NonAdminBackupStorageLocation) DeepCopy() *NonAdminBackupStorageLocation {
	if in == nil {
		return nil
	}
	out := new(NonAdminBackupStorageLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NonAdminBackupStorageLocation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminBackupStorageLocationList) DeepCopyInto(out *NonAdminBackupStorageLocationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NonAdminBackupStorageLocation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminBackupStorageLocationList.
func (in *NonAdminBackupStorageLocationList) DeepCopy() *NonAdminBackupStorageLocationList {
	if in == nil {
		return nil
	}
	out := new(NonAdminBackupStorageLocationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NonAdminBackupStorageLocationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminBackupStorageLocationRequest) DeepCopyInto(out *NonAdminBackupStorageLocationRequest) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	out.Spec = in.Spec
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminBackupStorageLocationRequest.
func (in *NonAdminBackupStorageLocationRequest) DeepCopy() *NonAdminBackupStorageLocationRequest {
	if in == nil {
		return nil
	}
	out := new(NonAdminBackupStorageLocationRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NonAdminBackupStorageLocationRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminBackupStorageLocationRequestList) DeepCopyInto(out *NonAdminBackupStorageLocationRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NonAdminBackupStorageLocationRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminBackupStorageLocationRequestList.
func (in *NonAdminBackupStorageLocationRequestList) DeepCopy() *NonAdminBackupStorageLocationRequestList {
	if in == nil {
		return nil
	}
	out := new(NonAdminBackupStorageLocationRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NonAdminBackupStorageLocationRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminBackupStorageLocationRequestSpec) DeepCopyInto(out *NonAdminBackupStorageLocationRequestSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminBackupStorageLocationRequestSpec.
func (in *NonAdminBackupStorageLocationRequestSpec) DeepCopy() *NonAdminBackupStorageLocationRequestSpec {
	if in == nil {
		return nil
	}
	out := new(NonAdminBackupStorageLocationRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminBackupStorageLocationRequestStatus) DeepCopyInto(out *NonAdminBackupStorageLocationRequestStatus) {
	*out = *in
	if in.SourceNonAdminBSL != nil {
		in, out := &in.SourceNonAdminBSL, &out.SourceNonAdminBSL
		*out = new(SourceNonAdminBSL)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminBackupStorageLocationRequestStatus.
func (in *NonAdminBackupStorageLocationRequestStatus) DeepCopy() *NonAdminBackupStorageLocationRequestStatus {
	if in == nil {
		return nil
	}
	out := new(NonAdminBackupStorageLocationRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminBackupStorageLocationSpec) DeepCopyInto(out *NonAdminBackupStorageLocationSpec) {
	*out = *in
	if in.BackupStorageLocationSpec != nil {
		in, out := &in.BackupStorageLocationSpec, &out.BackupStorageLocationSpec
		*out = new(v1.BackupStorageLocationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminBackupStorageLocationSpec.
func (in *NonAdminBackupStorageLocationSpec) DeepCopy() *NonAdminBackupStorageLocationSpec {
	if in == nil {
		return nil
	}
	out := new(NonAdminBackupStorageLocationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminBackupStorageLocationStatus) DeepCopyInto(out *NonAdminBackupStorageLocationStatus) {
	*out = *in
	if in.VeleroBackupStorageLocation != nil {
		in, out := &in.VeleroBackupStorageLocation, &out.VeleroBackupStorageLocation
		*out = new(VeleroBackupStorageLocation)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminBackupStorageLocationStatus.
func (in *NonAdminBackupStorageLocationStatus) DeepCopy() *NonAdminBackupStorageLocationStatus {
	if in == nil {
		return nil
	}
	out := new(NonAdminBackupStorageLocationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminDownloadRequest) DeepCopyInto(out *NonAdminDownloadRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminDownloadRequest.
func (in *NonAdminDownloadRequest) DeepCopy() *NonAdminDownloadRequest {
	if in == nil {
		return nil
	}
	out := new(NonAdminDownloadRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NonAdminDownloadRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminDownloadRequestList) DeepCopyInto(out *NonAdminDownloadRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NonAdminDownloadRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminDownloadRequestList.
func (in *NonAdminDownloadRequestList) DeepCopy() *NonAdminDownloadRequestList {
	if in == nil {
		return nil
	}
	out := new(NonAdminDownloadRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NonAdminDownloadRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminDownloadRequestSpec) DeepCopyInto(out *NonAdminDownloadRequestSpec) {
	*out = *in
	out.Target = in.Target
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminDownloadRequestSpec.
func (in *NonAdminDownloadRequestSpec) DeepCopy() *NonAdminDownloadRequestSpec {
	if in == nil {
		return nil
	}
	out := new(NonAdminDownloadRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminDownloadRequestStatus) DeepCopyInto(out *NonAdminDownloadRequestStatus) {
	*out = *in
	in.VeleroDownloadRequest.DeepCopyInto(&out.VeleroDownloadRequest)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminDownloadRequestStatus.
func (in *NonAdminDownloadRequestStatus) DeepCopy() *NonAdminDownloadRequestStatus {
	if in == nil {
		return nil
	}
	out := new(NonAdminDownloadRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminRestore) DeepCopyInto(out *NonAdminRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminRestore.
func (in *NonAdminRestore) DeepCopy() *NonAdminRestore {
	if in == nil {
		return nil
	}
	out := new(NonAdminRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NonAdminRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminRestoreList) DeepCopyInto(out *NonAdminRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NonAdminRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminRestoreList.
func (in *NonAdminRestoreList) DeepCopy() *NonAdminRestoreList {
	if in == nil {
		return nil
	}
	out := new(NonAdminRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NonAdminRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminRestoreSpec) DeepCopyInto(out *NonAdminRestoreSpec) {
	*out = *in
	if in.RestoreSpec != nil {
		in, out := &in.RestoreSpec, &out.RestoreSpec
		*out = new(v1.RestoreSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminRestoreSpec.
func (in *NonAdminRestoreSpec) DeepCopy() *NonAdminRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(NonAdminRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminRestoreStatus) DeepCopyInto(out *NonAdminRestoreStatus) {
	*out = *in
	if in.VeleroRestore != nil {
		in, out := &in.VeleroRestore, &out.VeleroRestore
		*out = new(VeleroRestore)
		(*in).DeepCopyInto(*out)
	}
	if in.DataMoverDataDownloads != nil {
		in, out := &in.DataMoverDataDownloads, &out.DataMoverDataDownloads
		*out = new(DataMoverDataDownloads)
		**out = **in
	}
	if in.FileSystemPodVolumeRestores != nil {
		in, out := &in.FileSystemPodVolumeRestores, &out.FileSystemPodVolumeRestores
		*out = new(FileSystemPodVolumeRestores)
		**out = **in
	}
	if in.QueueInfo != nil {
		in, out := &in.QueueInfo, &out.QueueInfo
		*out = new(QueueInfo)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminRestoreStatus.
func (in *NonAdminRestoreStatus) DeepCopy() *NonAdminRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(NonAdminRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageLocation) DeepCopyInto(out *ObjectStorageLocation) {
	*out = *in
	if in.CACert != nil {
		in, out := &in.CACert, &out.CACert
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStorageLocation.
func (in *ObjectStorageLocation) DeepCopy() *ObjectStorageLocation {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodConfig) DeepCopyInto(out *PodConfig) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ResourceAllocations.DeepCopyInto(&out.ResourceAllocations)
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodConfig.
func (in *PodConfig) DeepCopy() *PodConfig {
	if in == nil {
		return nil
	}
	out := new(PodConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueInfo) DeepCopyInto(out *QueueInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueInfo.
func (in *QueueInfo) DeepCopy() *QueueInfo {
	if in == nil {
		return nil
	}
	out := new(QueueInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResticConfig) DeepCopyInto(out *ResticConfig) {
	*out = *in
	in.NodeAgentCommonFields.DeepCopyInto(&out.NodeAgentCommonFields)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResticConfig.
func (in *ResticConfig) DeepCopy() *ResticConfig {
	if in == nil {
		return nil
	}
	out := new(ResticConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetainPolicy) DeepCopyInto(out *RetainPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetainPolicy.
func (in *RetainPolicy) DeepCopy() *RetainPolicy {
	if in == nil {
		return nil
	}
	out := new(RetainPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotLocation) DeepCopyInto(out *SnapshotLocation) {
	*out = *in
	if in.Velero != nil {
		in, out := &in.Velero, &out.Velero
		*out = new(v1.VolumeSnapshotLocationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotLocation.
func (in *SnapshotLocation) DeepCopy() *SnapshotLocation {
	if in == nil {
		return nil
	}
	out := new(SnapshotLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceNonAdminBSL) DeepCopyInto(out *SourceNonAdminBSL) {
	*out = *in
	if in.RequestedSpec != nil {
		in, out := &in.RequestedSpec, &out.RequestedSpec
		*out = new(v1.BackupStorageLocationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceNonAdminBSL.
func (in *SourceNonAdminBSL) DeepCopy() *SourceNonAdminBSL {
	if in == nil {
		return nil
	}
	out := new(SourceNonAdminBSL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageType) DeepCopyInto(out *StorageType) {
	*out = *in
	if in.ObjectStorage != nil {
		in, out := &in.ObjectStorage, &out.ObjectStorage
		*out = new(ObjectStorageLocation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageType.
func (in *StorageType) DeepCopy() *StorageType {
	if in == nil {
		return nil
	}
	out := new(StorageType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VeleroBackup) DeepCopyInto(out *VeleroBackup) {
	*out = *in
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(v1.BackupSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(v1.BackupStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VeleroBackup.
func (in *VeleroBackup) DeepCopy() *VeleroBackup {
	if in == nil {
		return nil
	}
	out := new(VeleroBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VeleroBackupStorageLocation) DeepCopyInto(out *VeleroBackupStorageLocation) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(v1.BackupStorageLocationStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VeleroBackupStorageLocation.
func (in *VeleroBackupStorageLocation) DeepCopy() *VeleroBackupStorageLocation {
	if in == nil {
		return nil
	}
	out := new(VeleroBackupStorageLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VeleroConfig) DeepCopyInto(out *VeleroConfig) {
	*out = *in
	if in.FeatureFlags != nil {
		in, out := &in.FeatureFlags, &out.FeatureFlags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultPlugins != nil {
		in, out := &in.DefaultPlugins, &out.DefaultPlugins
		*out = make([]DefaultPlugin, len(*in))
		copy(*out, *in)
	}
	if in.CustomPlugins != nil {
		in, out := &in.CustomPlugins, &out.CustomPlugins
		*out = make([]CustomPlugin, len(*in))
		copy(*out, *in)
	}
	if in.PodConfig != nil {
		in, out := &in.PodConfig, &out.PodConfig
		*out = new(PodConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultVolumesToFSBackup != nil {
		in, out := &in.DefaultVolumesToFSBackup, &out.DefaultVolumesToFSBackup
		*out = new(bool)
		**out = **in
	}
	if in.DefaultSnapshotMoveData != nil {
		in, out := &in.DefaultSnapshotMoveData, &out.DefaultSnapshotMoveData
		*out = new(bool)
		**out = **in
	}
	if in.DisableInformerCache != nil {
		in, out := &in.DisableInformerCache, &out.DisableInformerCache
		*out = new(bool)
		**out = **in
	}
	if in.ClientBurst != nil {
		in, out := &in.ClientBurst, &out.ClientBurst
		*out = new(int)
		**out = **in
	}
	if in.ClientQPS != nil {
		in, out := &in.ClientQPS, &out.ClientQPS
		*out = new(int)
		**out = **in
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = new(server.Args)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VeleroConfig.
func (in *VeleroConfig) DeepCopy() *VeleroConfig {
	if in == nil {
		return nil
	}
	out := new(VeleroConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VeleroDeleteBackupRequest) DeepCopyInto(out *VeleroDeleteBackupRequest) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(v1.DeleteBackupRequestStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VeleroDeleteBackupRequest.
func (in *VeleroDeleteBackupRequest) DeepCopy() *VeleroDeleteBackupRequest {
	if in == nil {
		return nil
	}
	out := new(VeleroDeleteBackupRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VeleroDownloadRequest) DeepCopyInto(out *VeleroDownloadRequest) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(v1.DownloadRequestStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VeleroDownloadRequest.
func (in *VeleroDownloadRequest) DeepCopy() *VeleroDownloadRequest {
	if in == nil {
		return nil
	}
	out := new(VeleroDownloadRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VeleroRestore) DeepCopyInto(out *VeleroRestore) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(v1.RestoreStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VeleroRestore.
func (in *VeleroRestore) DeepCopy() *VeleroRestore {
	if in == nil {
		return nil
	}
	out := new(VeleroRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeOptions) DeepCopyInto(out *VolumeOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeOptions.
func (in *VolumeOptions) DeepCopy() *VolumeOptions {
	if in == nil {
		return nil
	}
	out := new(VolumeOptions)
	in.DeepCopyInto(out)
	return out
}
