# This rule is not used by the project oadp-nac itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over oadp.openshift.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: oadp-nac
    app.kubernetes.io/managed-by: kustomize
  name: nonadmindownloadrequest-admin-role
rules:
- apiGroups:
  - oadp.openshift.io
  resources:
  - nonadmindownloadrequests
  verbs:
  - '*'
- apiGroups:
  - oadp.openshift.io
  resources:
  - nonadmindownloadrequests/status
  verbs:
  - get
