apiVersion: v1
kind: List
items:
  - apiVersion: snapshot.storage.k8s.io/v1
    kind: VolumeSnapshotClass
    metadata:
      name: example-snapclass
      labels:
        velero.io/csi-volumesnapshot-class: 'true'
      annotations:
        snapshot.storage.kubernetes.io/is-default-class: 'true'
    driver: ebs.csi.aws.com
    deletionPolicy: Retain