apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: oadp-default-deny-labelled
  labels:
    app.kubernetes.io/name: oadp-networkpolicy
    app.kubernetes.io/component: network-security
    app.kubernetes.io/part-of: oadp-operator
    app.kubernetes.io/managed-by: olm
spec:
  # Limited Default Deny Policy:
  # This policy selects pods managed by oadp-operator and blocks all traffic by default,
  # except for the specific ingress/egress rules defined below.
  # It allows OADP to coexist with other workloads in the same namespace.
  podSelector:
    matchLabels:
      app.kubernetes.io/managed-by: "oadp-operator"
  policyTypes:
    - Ingress
    - Egress
  ingress:
  - from:
    - podSelector: {}
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-monitoring
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-user-workload-monitoring
    ports:
    - protocol: TCP
      port: 8085
    - protocol: TCP
      port: 8443
  - ports:
    - protocol: TCP
      port: 9443
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443
    # Explicitly allow access to DNS
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: openshift-dns
        podSelector:
          matchLabels:
            dns.operator.openshift.io/daemonset-dns: default
      ports:
      - protocol: UDP
        port: 53
      - protocol: TCP
        port: 53
      - protocol: UDP
        port: 5353
      - protocol: TCP
        port: 5353
    # Explicitly allow access to Kubernetes API Server
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: default
      ports:
      - protocol: TCP
        port: 443
    # Explicitly allow access to OpenShift API Server
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: openshift-apiserver
      ports:
      - protocol: TCP
        port: 443
    # Explicitly allow access to Kubernetes API Server (OpenShift Namespace)
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: openshift-kube-apiserver
      ports:
      - protocol: TCP
        port: 443
      - protocol: TCP
        port: 6443
