name: docs-actions
on:
  pull_request:
    paths:
      - '**/**.md'
      - '.github/workflows/docs-actions.yml'
      - '!vendor'
jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Link Checker
      uses: lycheeverse/lychee-action@v1.0.8
      with:
        args: --verbose --no-progress --exclude .*dog8code\.com.* --exclude https://quay.io/cnr -- docs/**/*.md *.md
    - run: if grep 'Errors in' ./lychee/out.md; then fail; fi
