name: docs-actions
on:
  pull_request:
    paths:
      - '**/**.md'
jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Link Checker
      uses: lycheeverse/lychee-action@v1.0.8
      with:
        args: --verbose --no-progress **/*.md
    - run: if grep 'Errors in' ./lychee/out.md; then fail; fi
